######################## default configuration ####################
baseURL = "https://ensign.rotational.dev"
title = "Hugo documentation theme"
theme = "godocs-2"

# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "UTC"

# google analytics
googleAnalytics = "G-XMWR6VW3VJ"

# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.
# disqusShortname = "ensign-docs"

# disable language
disableLanguages = ["fr"]  # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = false

# (Optional) Set this to true to enable 'Last Modified by' date and git author
#  information on 'doc' type pages.
enableGitInfo = true

# (Optional) Theme is intended for documentation use, therefore it doesn't render taxonomy.
# You can remove related files with config below
disableKinds = ["taxonomy", "term"]
[taxonomies]
    category = "categories"
    tag = "tags"

################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1

################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 2


############################# Build ##############################
[build]
writeStats = true

############################# Outputs ##############################
[outputs]
home = ["HTML"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'catppuccin-mocha' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

[menu]
[[menu.footer]]
  name = 'GitHub'
  url = 'https://github.com/rotationalio/ensign'
  weight = 10
[[menu.footer]]
  name = 'Rotational Labs'
  url = 'https://rotational.io'
  weight = 20

############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
