{
 "title": "Ensign",
 "description": "The Primary Ensign Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Event Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Online Publishers",
   "type": "gauge",
   "description": "The number of currently online publishers.",
   "gridPos": { "h": 8, "w": 6, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ensign_online_publishers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Online Subscribers",
   "type": "gauge",
   "description": "The number of currently connected subscribers",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ensign_online_subscribers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of Events",
   "type": "stat",
   "description": "The total number of events published for all time.",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ensign_events)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event Ingestion",
   "type": "timeseries",
   "description": "The rate at which events are being published in the system.",
   "gridPos": { "h": 8, "w": 21, "x": 1, "y": 9 },
   "targets": [
    {
     "expr": "rate(ensign_events[$__rate_interval]) ",
     "legendFormat": "System"
    }
   ]
  },
  {
   "title": "gRPC Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "RPC Methods",
   "type": "barchart",
   "description": "The number of RPC calls per minute on the server",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 18 },
   "targets": [
    {
     "expr": "sum by(method) (rate(grpc_server_started_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streaming Messages",
   "type": "timeseries",
   "description": "The number of streaming messages being sent and received per minute",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(grpc_server_stream_messages_sent[$__rate_interval])",
     "legendFormat": "{{method}} Sent"
    },
    {
     "expr": "rate(grpc_server_stream_messages_recv[$__rate_interval])",
     "legendFormat": "{{method}} Recv"
    }
   ]
  },
  {
   "title": "Duration Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 26 },
   "targets": [
    {
     "expr": "avg by(method) (grpc_server_handler_duration_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(code) (irate(grpc_server_handled_total{code!=\"OK\"}[5m:5m]) * 60)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Ensign Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "The percentage of CPU usage of the Go process measured as the rate of cpu seconds every 30 seconds times 100.",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 35 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Concurrency",
   "type": "timeseries",
   "description": "The number of active go routines and OS threads in use by the Ensign process",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 35 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "go routines" },
    { "expr": "go_threads", "legendFormat": "threads" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Displays the memory usage of the Ensign nodes",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 43 },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes / 1048576",
     "legendFormat": "vmem"
    },
    {
     "expr": "go_memstats_heap_alloc_bytes  / 1048576",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_sys_bytes / 1048576",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "description": "The total number of mallocs less total freed gives you the total number of objects in memory.",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 43 },
   "targets": [
    { "expr": "go_memstats_heap_objects", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Heap Alloc Rate",
   "type": "timeseries",
   "description": "The number of MiB allocated per second.",
   "gridPos": { "h": 8, "w": 7, "x": 1, "y": 51 },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[30s]) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Object Usage Rate",
   "type": "timeseries",
   "description": "The rate at which objects are being created and freed.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 51 },
   "targets": [
    {
     "expr": "rate(go_memstats_mallocs_total[30s])",
     "legendFormat": "alloc/s"
    },
    {
     "expr": "rate(go_memstats_frees_total[30s])",
     "legendFormat": "free/s"
    },
    {
     "expr": "rate(go_memstats_lookups_total[30s])",
     "legendFormat": "lookup/s"
    }
   ]
  },
  {
   "title": "Current Heap",
   "type": "gauge",
   "description": "Number of bytes allocated and still in use.",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1048576",
     "legendFormat": "MiB"
    }
   ]
  }
 ]
}