// react query query keys
export const RQK = {
  CREATE_ACCOUNT: 'createAccount',
  LOGIN: 'login',
  TENANTS: 'tenants',
  CREATE_KEY: 'createAPIKey',
  PROJECT: 'project-detail',
  PROJECTS: 'projects',
  PROJECT_STATS: 'project-stats',
  TENANTS_STATS: 'tenant-stats',
  TOPICS: 'topics',
  TOPIC: 'topic',
  MEMBER_LIST: 'memberList',
  MEMBER_DETAIL: 'memberDetail',
  ORG_DETAIL: 'orgDetail',
  VERIFY_EMAIL: 'verify-email',
  API_KEYS: 'apiKeys',
  QUICK_VIEW: 'quickView',
  PERMISSIONS: 'permissions',
  PROJECT_API_KEYS: 'projectAPIKeys',
  ORGANIZATION_LIST: 'organizationList',
  REFETCH_PROJECTS: 'refetchProjects',
  PROJECT_QUICK_VIEW: 'projectQuickView',
  TOPIC_STATS: 'topic-stats',
  PROFILE: 'profile',
} as const;
