FROM nginx

COPY web/placeholder/landing/index.html /usr/share/nginx/html/
COPY web/placeholder/landing/favicon.png /usr/share/nginx/html/
COPY web/placeholder/landing/rotational-logo.svg /usr/share/nginx/html/
COPY web/placeholder/landing/otter-floating.svg /usr/share/nginx/html/