FROM nginx

COPY web/placeholder/landing/index.html /usr/share/nginx/html/
COPY web/placeholder/landing/favicon.ico /usr/share/nginx/html/
COPY web/placeholder/landing/rotational-logo.svg /usr/share/nginx/html/